### ISSUE TITLE
Export private key feature generate a string prepended with 0x.

### ISSUE THREAD

**Issue by sophoah** [harmony-one/onewallet#11]
The export private key feature generate a string prepended with 0x.

the import will only work if we remove the 0x.

**Comment by raptor1001** [comment]
@sophoah in this wallet, the import will work even though it has the 0x

**Comment by sophoah** [comment]
@raptor1001 i actually tried to import and it didn't work until i removed the 0x.

**Comment by yelllowsin** [comment]
@raptor1001 just tested on v1.0.0 and this has been fixed. You can close this issue.
