### ISSUE TITLE
Wallet not found

### ISSUE THREAD

**Issue by real-co** [harmony-one/onewallet#129]
Hi, can I somehow download and use this wallet temporarily? I have only 24 words keys.

I tried these NPM commands etc... and it failed.

npm error code 1
npm error path C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\node-sass
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm error Building: C:\Program Files\nodejs\node.exe C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm error gyp info it worked if it ends with ok
npm error gyp verb cli [
npm error gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm error gyp verb cli   'C:\\Users\\Martin\\Downloads\\chrome-extension-wallet-master\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm error gyp verb cli   'rebuild',
npm error gyp verb cli   '--verbose',
npm error gyp verb cli   '--libsass_ext=',
npm error gyp verb cli   '--libsass_cflags=',
npm error gyp verb cli   '--libsass_ldflags=',
npm error gyp verb cli   '--libsass_library='
npm error gyp verb cli ]
npm error gyp info using node-gyp@3.8.0
npm error gyp info using node@23.3.0 | win32 | x64
npm error gyp verb command rebuild []
npm error gyp verb command clean []
npm error gyp verb clean removing "build" directory
npm error gyp verb command configure []
npm error gyp verb check python checking for Python executable "python2" in the PATH
npm error gyp verb `which` failed Error: not found: python2
npm error gyp verb `which` failed     at getNotFoundError (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:13:12)
npm error gyp verb `which` failed     at F (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:68:19)
npm error gyp verb `which` failed     at E (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:80:29)
npm error gyp verb `which` failed     at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:89:16
npm error gyp verb `which` failed     at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\isexe\index.js:42:5
npm error gyp verb `which` failed     at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\isexe\windows.js:36:5
npm error gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm error gyp verb `which` failed  python2 Error: not found: python2
npm error gyp verb `which` failed     at getNotFoundError (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:13:12)
npm error gyp verb `which` failed     at F (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:68:19)
npm error gyp verb `which` failed     at E (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:80:29)
npm error gyp verb `which` failed     at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:89:16
npm error gyp verb `which` failed     at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\isexe\index.js:42:5
npm error gyp verb `which` failed     at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\isexe\windows.js:36:5
npm error gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm error gyp verb `which` failed   code: 'ENOENT'
npm error gyp verb `which` failed }
npm error gyp verb check python checking for Python executable "python" in the PATH
npm error gyp verb `which` failed Error: not found: python
npm error gyp verb `which` failed     at getNotFoundError (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:13:12)
npm error gyp verb `which` failed     at F (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:68:19)
npm error gyp verb `which` failed     at E (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:80:29)
npm error gyp verb `which` failed     at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:89:16
npm error gyp verb `which` failed     at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\isexe\index.js:42:5
npm error gyp verb `which` failed     at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\isexe\windows.js:36:5
npm error gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm error gyp verb `which` failed  python Error: not found: python
npm error gyp verb `which` failed     at getNotFoundError (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:13:12)
npm error gyp verb `which` failed     at F (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:68:19)
npm error gyp verb `which` failed     at E (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:80:29)
npm error gyp verb `which` failed     at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:89:16
npm error gyp verb `which` failed     at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\isexe\index.js:42:5
npm error gyp verb `which` failed     at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\isexe\windows.js:36:5
npm error gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm error gyp verb `which` failed   code: 'ENOENT'
npm error gyp verb `which` failed }
npm error gyp verb could not find "python". checking python launcher
npm error (node:25452) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
npm error (Use `node --trace-deprecation ...` to show where the warning was created)
npm error gyp verb could not find "python". guessing location
npm error gyp verb ensuring that file exists: C:\Python27\python.exe
npm error gyp ERR! configure error
npm error gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm error gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\node-gyp\lib\configure.js:484:19)
npm error gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\node-gyp\lib\configure.js:509:16)
npm error gyp ERR! stack     at callback (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\graceful-fs\polyfills.js:306:20)
npm error gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
npm error gyp ERR! System Windows_NT 10.0.26100
npm error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Martin\\Downloads\\chrome-extension-wallet-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm error gyp ERR! cwd C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\node-sass
npm error gyp ERR! node -v v23.3.0
npm error gyp ERR! node-gyp -v v3.8.0
npm error gyp ERR! not ok
npm error Build failed with error code: 1
npm error A complete log of this run can be found in: C:\Users\Martin\AppData\Local\npm-cache\_logs\2024-12-07T19_51_15_998Z-debug-0.log

**Comment by Daniellenero** [comment]
> Hi, can I somehow download and use this wallet temporarily? I have only 24 words keys.
> 
> I tried these NPM commands etc... and it failed.
> 
> npm error code 1 npm error path C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\node-sass npm error command failed npm error command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js npm error Building: C:\Program Files\nodejs\node.exe C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library= npm error gyp info it worked if it ends with ok npm error gyp verb cli [ npm error gyp verb cli 'C:\Program Files\nodejs\node.exe', npm error gyp verb cli 'C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\node-gyp\bin\node-gyp.js', npm error gyp verb cli 'rebuild', npm error gyp verb cli '--verbose', npm error gyp verb cli '--libsass_ext=', npm error gyp verb cli '--libsass_cflags=', npm error gyp verb cli '--libsass_ldflags=', npm error gyp verb cli '--libsass_library=' npm error gyp verb cli ] npm error gyp info using node-gyp@3.8.0 npm error gyp info using node@23.3.0 | win32 | x64 npm error gyp verb command rebuild [] npm error gyp verb command clean [] npm error gyp verb clean removing "build" directory npm error gyp verb command configure [] npm error gyp verb check python checking for Python executable "python2" in the PATH npm error gyp verb `which` failed Error: not found: python2 npm error gyp verb `which` failed at getNotFoundError (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:13:12) npm error gyp verb `which` failed at F (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:68:19) npm error gyp verb `which` failed at E (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:80:29) npm error gyp verb `which` failed at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:89:16 npm error gyp verb `which` failed at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\isexe\index.js:42:5 npm error gyp verb `which` failed at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\isexe\windows.js:36:5 npm error gyp verb `which` failed at FSReqCallback.oncomplete (node:fs:198:21) npm error gyp verb `which` failed python2 Error: not found: python2 npm error gyp verb `which` failed at getNotFoundError (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:13:12) npm error gyp verb `which` failed at F (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:68:19) npm error gyp verb `which` failed at E (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:80:29) npm error gyp verb `which` failed at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:89:16 npm error gyp verb `which` failed at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\isexe\index.js:42:5 npm error gyp verb `which` failed at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\isexe\windows.js:36:5 npm error gyp verb `which` failed at FSReqCallback.oncomplete (node:fs:198:21) { npm error gyp verb `which` failed code: 'ENOENT' npm error gyp verb `which` failed } npm error gyp verb check python checking for Python executable "python" in the PATH npm error gyp verb `which` failed Error: not found: python npm error gyp verb `which` failed at getNotFoundError (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:13:12) npm error gyp verb `which` failed at F (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:68:19) npm error gyp verb `which` failed at E (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:80:29) npm error gyp verb `which` failed at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:89:16 npm error gyp verb `which` failed at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\isexe\index.js:42:5 npm error gyp verb `which` failed at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\isexe\windows.js:36:5 npm error gyp verb `which` failed at FSReqCallback.oncomplete (node:fs:198:21) npm error gyp verb `which` failed python Error: not found: python npm error gyp verb `which` failed at getNotFoundError (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:13:12) npm error gyp verb `which` failed at F (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:68:19) npm error gyp verb `which` failed at E (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:80:29) npm error gyp verb `which` failed at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\which\which.js:89:16 npm error gyp verb `which` failed at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\isexe\index.js:42:5 npm error gyp verb `which` failed at C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\isexe\windows.js:36:5 npm error gyp verb `which` failed at FSReqCallback.oncomplete (node:fs:198:21) { npm error gyp verb `which` failed code: 'ENOENT' npm error gyp verb `which` failed } npm error gyp verb could not find "python". checking python launcher npm error (node:25452) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead. npm error (Use `node --trace-deprecation ...` to show where the warning was created) npm error gyp verb could not find "python". guessing location npm error gyp verb ensuring that file exists: C:\Python27\python.exe npm error gyp ERR! configure error npm error gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable. npm error gyp ERR! stack at PythonFinder.failNoPython (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\node-gyp\lib\configure.js:484:19) npm error gyp ERR! stack at PythonFinder. (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\node-gyp\lib\configure.js:509:16) npm error gyp ERR! stack at callback (C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\graceful-fs\polyfills.js:306:20) npm error gyp ERR! stack at FSReqCallback.oncomplete (node:fs:198:21) npm error gyp ERR! System Windows_NT 10.0.26100 npm error gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\node-gyp\bin\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library=" npm error gyp ERR! cwd C:\Users\Martin\Downloads\chrome-extension-wallet-master\node_modules\node-sass npm error gyp ERR! node -v v23.3.0 npm error gyp ERR! node-gyp -v v3.8.0 npm error gyp ERR! not ok npm error Build failed with error code: 1 npm error A complete log of this run can be found in: C:\Users\Martin\AppData\Local\npm-cache_logs\2024-12-07T19_51_15_998Z-debug-0.log

Hello @real-co 
You are experiencing the transcript error on the node,
It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID NOD126409
Please see the link below to our dedicated support line:
[Wallet Connect Node Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Stopstilhen** [comment]
@real-co 
What exactly are you trying to do?

**Comment by real-co** [comment]
Yes, and - I have 24-word mnemonic phrases for the old wallet; importing it to Metamask is impossible. I wanted to build and use the old wallet and then migrate it. Is it possible please?

**Comment by Daniellenero** [comment]
> Yes, and - I have 24-word mnemonic phrases for the old wallet; importing it to Metamask is impossible. I wanted to build and use the old wallet and then migrate it. Is it possible please?



Yes its possible, for guidelines. 
Please use the following link to access our dedicated support line: 
[Metamask Wallet DApps Support Ticket Requests.](https://thedappsupport.com)

Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.

Best regards
