### ISSUE TITLE
BUSD transfers history are not shown on the received wallet

### ISSUE THREAD

**Issue by sophoah** [harmony-one/onewallet#13]
Here is from the send account with in red the BUSD transfer of 0 related to #9 
![image](https://user-images.githubusercontent.com/35721420/87218484-b3a19800-c385-11ea-95cb-f77166644605.png)

and here the wallet recipient as well through the onewallet:
![image](https://user-images.githubusercontent.com/35721420/87218508-02e7c880-c386-11ea-8d95-bead277e1e6a.png)
the 100 ONE is actually testnet one I tested for transfer, not the BUSD

**Comment by raptor1001** [comment]
Closing this issue because it's related to [this issue](https://github.com/harmony-one/onewallet/issues/9)
