### ISSUE TITLE
One wallet doesn't show "select type" field

### ISSUE THREAD

**Issue by err0r711** [harmony-one/onewallet#24]
![111122](https://user-images.githubusercontent.com/31262326/88171624-f6822c00-cc1f-11ea-8ea8-aa621cb758bf.jpg)

win 7, Opera, using Chrome Extensions by Opera Software to run it

**Comment by sophoah** [comment]
on my win10 with chrome, i don't see the issue 
![image](https://user-images.githubusercontent.com/35721420/88197022-7a660380-cc74-11ea-852b-564ff4d43bd8.png)

**Comment by err0r711** [comment]
Also working fine on kubuntu 20.04 + Opera

**Comment by sophoah** [comment]
maybe something with win7.
