### ISSUE TITLE
One wallet -network field- not visible

### ISSUE THREAD

**Issue by err0r711** [harmony-one/onewallet#25]
![test1](https://user-images.githubusercontent.com/31262326/88172299-0cdcb780-cc21-11ea-8e53-3f240988d3af.jpg)

win 7, Opera, using hrome Extensions by Opera Software to run it

**Comment by mirrormirage0** [comment]
This is probably an issue only on Windows 7 + Opera.

On Windows 10 + Opera, it looks okay.
![image](https://user-images.githubusercontent.com/29485946/88225590-ce281b00-cc7b-11ea-9221-9c34ff9e901e.png)

**Comment by err0r711** [comment]
Also working fine on kubuntu 20.04 + Opera

**Comment by sophoah** [comment]
i think let's close this issue, i am not sure many are still using win 7 :)

**Comment by err0r711** [comment]
> i think let's close this issue, i am not sure many are still using win 7 :)

https://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide

Win7 | 19.79%, I also thought it was less than 5%.
