### ISSUE TITLE
UI Bug when importing a keystore filename

### ISSUE THREAD

**Issue by sophoah** [harmony-one/onewallet#26]
See screenshot :
![image](https://user-images.githubusercontent.com/35721420/88198133-f90f7080-cc75-11ea-95f0-73456d49fbb0.png)
![image](https://user-images.githubusercontent.com/35721420/88198858-bc904480-cc76-11ea-875b-36fa83768831.png)

**Comment by raptor1001** [comment]
![image](https://user-images.githubusercontent.com/54774811/88330586-78d22500-cce0-11ea-9a99-ac670334f637.png)
it cames out like this on my pc

**Comment by sophoah** [comment]
@raptor1001 I am on windows 10

**Comment by raptor1001** [comment]
@sophoah is this fixed? can we close this?

**Comment by raptor1001** [comment]
is fixed
