### ISSUE TITLE
keystore import is not working

### ISSUE THREAD

**Issue by sophoah** [harmony-one/onewallet#27]
Importing a keystore is not working.

How I got the keystore file:
1) copy pasting the content of the keystore file
2) download through sftp the keystore file

for both file, when trying to import i can go all the way to :
  
![image](https://user-images.githubusercontent.com/35721420/88199095-02e5a380-cc77-11ea-8f8a-e5235ffc0aa9.png)

however, after clicking ok, the tab closed but the extension doesn't have the new imported wallet.

**Comment by sophoah** [comment]
just tried to use private key and it also doesn't import (or at least i can't see the new wallet created)

I tested creating a new wallet, and that one no issue.

**Comment by raptor1001** [comment]
@sophoah can you send me the private key and key store file for the test? You can PM me in the discord

**Comment by raptor1001** [comment]
importing with the private key is working. I just tested. @sophoah

**Comment by sophoah** [comment]
i am closing this one as i also tested the import and it works now.
