### ISSUE TITLE
UI bug : HRC20 token shows NaN

### ISSUE THREAD

**Issue by sophoah** [harmony-one/onewallet#28]
In the account tab, when non shard 0 is elected, the HRC20 token will show NaN:

![image](https://user-images.githubusercontent.com/35721420/88200845-46411180-cc79-11ea-8f9c-905dd242bd70.png)

So I know HRC20 for now only works on shard 0 however, having a different message than NaN mentioning about the limitation would be great

**Comment by raptor1001** [comment]
@sophoah Is this fixed? Can we close this?

**Comment by raptor1001** [comment]
this is fixed
