### ISSUE TITLE
Cannot add custom HRC-20 Token 

### ISSUE THREAD

**Issue by mirrormirage0** [harmony-one/onewallet#29]
ONE wallet shows error "Contract address is invalid" when trying to add a custom HRC20 Token contract

![image](https://user-images.githubusercontent.com/29485946/88284556-a928bc00-ccfe-11ea-8e88-97794c92a947.png)

Testnet Contract address #1  0x2450bcede73c289c105e7ff9c7ed4df223cc92f8 
Ticker POPS
Decimal 12

Testnet Contract address #2 0x494dfd32b474a2a35020bde7b3da37ef2b61a90d
Ticker MIRROR
Decimal 18

Both contracts can be interacted through ABI explorer and transactions visible on explorer.

Sample Token transfer (MIRROR token) 
https://explorer.testnet.harmony.one/#/tx/0x557977bde88448795fe3cec3a88523810af2163755e65691806f65ddaac067ac

**Comment by sophoah** [comment]
I confirmed the same problem as @mirrormirage0 used the POPS contract address I created. I tested without 0x but no luck. The HRC20 token works as it was tested using a contract interactor UI https://dev.ript.io/tokentools/thecontractor

**Comment by mirrormirage0** [comment]
Issue is resolved in latest version downloaded on 7/24. https://github.com/harmony-one/onewallet/releases/download/v1.0.0/Harmony_Wallet_v1.0.0.zip 
_Kindly follow better naming convention for releases so that its easier to track which version resolved the issue_ 

![image](https://user-images.githubusercontent.com/29485946/88414201-86290580-cded-11ea-81e8-ea077097ec81.png)
