### ISSUE TITLE
Cannot Claim Staking Reward - defaults to maximum amount, does not allow to edit

### ISSUE THREAD

**Issue by mirrormirage0** [harmony-one/onewallet#32]
![image](https://user-images.githubusercontent.com/29485946/88415966-69420180-cdf0-11ea-992f-6c13116cd06d.png)

**Comment by raptor1001** [comment]
@mirrormirage0 it's working on my side. I can claim the rewards with the onewallet. What is not working on your side?

**Comment by mirrormirage0** [comment]
Closing this. Forgot that amount field is indeed un-editable in all wallet versions :)
