### ISSUE TITLE
HRC20 contract address bug between mainnet/testnet

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/onewallet#36]
So i added a hrc20 token to testnet on my onewallet, but it shows just there and not on mainnet too. When i switch over to mainnet and want to add the same on there it says it already exists, yet cant see it on mainnet:

NOTE: first screenshot its testnet network selected above, 2nd and 3rd its mainnet

![3](https://user-images.githubusercontent.com/55639830/89290517-4538b880-d659-11ea-9ed8-dfd1df26bf88.png)
![2](https://user-images.githubusercontent.com/55639830/89290522-47027c00-d659-11ea-81bd-1d7c9c182a0c.png)
![1](https://user-images.githubusercontent.com/55639830/89290529-4964d600-d659-11ea-91dd-3d8010c47155.png)

**Comment by raptor1001** [comment]
if that token is deployed to the mainnet, the contact address should be different. You can't add the testnet contact address to the mainnet @mindstyle85

**Comment by mindstyle85** [comment]
discussed this with him on discord, the feature to remove smart contracts/hrc tokens is coming, so closing this
