### ISSUE TITLE
UI Bug - Adding new HRC20 token gives only CAPS on "token symbol" input

### ISSUE THREAD

**Issue by JB273** [harmony-one/onewallet#37]
When adding a new HRC20 token to the wallet, it show only Capital letters.
Actually when you type the correct value it displays correct after creation, but you don't see it during the creation of the HRC20 token.

Typing:
![image](https://user-images.githubusercontent.com/54506968/89722944-31da7400-d9f0-11ea-9093-1210b412a88a.png)

Displays:
![image](https://user-images.githubusercontent.com/54506968/89722948-41f25380-d9f0-11ea-90b0-477ec8703b05.png)

**Comment by raptor1001** [comment]
is fixed
