### ISSUE TITLE
1/ Mnemonic mismatch & 2/ failure to see extension while connecting

### ISSUE THREAD

**Issue by gizemcakil** [harmony-one/onewallet#39]
From Maker demo users:
1/
![Untitled-2](https://user-images.githubusercontent.com/45907268/89815442-abaa5480-daf9-11ea-9eea-d6cd9d5f5432.png)
 
2/
![Untitled-3](https://user-images.githubusercontent.com/45907268/89815476-b6fd8000-daf9-11ea-99f8-200acba7f887.png)

**Comment by raptor1001** [comment]
@gizemcakil the second issue should be the issue of the maker web app. Do you know who has developed that website?

**Comment by gizemcakil** [comment]
@raptor1001 if it's Maker website related, then it can be ignored. Yuriy developed it.

**Comment by raptor1001** [comment]
will investigate this later
