### ISSUE TITLE
hrc20 token sending issue

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/onewallet#45]
i tried to test it and tried sending some VIP hrc20 tokens to its own contract address: 0x162ba1dc64ebf54b4c593665a12f448959ff26b5

it let me through, but then the tx failed in the end (sanity check maybe)

what the real problem is, once i did that, now every address i input as the receiver (when trying to send VIP tokens) is changed into bech32 format of the contract address 0x162ba1dc64ebf54b4c593665a12f448959ff26b5, which is https://explorer.harmony.one/#/address/0x162ba1dc64ebf54b4c593665a12f448959ff26b5

as you can see on the tx history page, all my attempts were as if sent to this address, although i was sending them to a completely legit address that i own

**Comment by JB273** [comment]
Can confirm this added to that doesn't work with Ledger also! (but this is obvious...).

**Comment by raptor1001** [comment]
I don't understand the issue. Sorry

**Comment by mindstyle85** [comment]
he now understand, went through him on discord, but looks like this is a general issue with the hrc token sending from onewallet, not because i tried to send to its own smart contract first

**Comment by raptor1001** [comment]
Use enough gas limit. Then it would succeed.

**Comment by raptor1001** [comment]
is fixed
