### ISSUE TITLE
incorrect balance

### ISSUE THREAD

**Issue by dakeshi** [harmony-one/onewallet#51]
# description
showing incorrect balance for ONE token and hrc20 token. it displays zero on balance regardless my real balance and type of tokens(one or hrc20 tokens)

# reprouduction
- import previous harmony wallet
- check ONE token balance with shard 0.
- add hrc20 token, in this case SEED. contract address is 0x793DAC3Ec4969A5BEE684BcF4290d52feB8F51b4
- check SEED token balance

# result
incorrect balance(just showing zero on balance)

# expected result
showing their balance correctly. 

# env
version: 1.0.2

**Comment by dakeshi** [comment]
interesting..issue has gone..um. it might be temporarily issue (like networking)

**Comment by sophoah** [comment]
Great to hear the issue is gone.

one way to verify is to check directly on the explorer : 
can you verify the balance on the explorer : 
- mainnet : https://explorer-beta.harmony.one/
- testnet : http://hrc20.easy-staking.com:8080/#/

**Comment by dakeshi** [comment]
@sophoah thanks for sharing those links. I can see the current SEED balance correctly on https://explorer-beta.harmony.one/ but I can not figure out SEED on HRC20 balance page using http://hrc20.easy-staking.com:8080/#/

![Explorer___Harmony](https://user-images.githubusercontent.com/8563047/91372541-db25c480-e84e-11ea-8c50-eaabf8cb7f0e.png)
