### ISSUE TITLE
Extension interacting with non-blockchain site and causing website functions to fail

### ISSUE THREAD

**Issue by michaelotis** [harmony-one/onewallet#53]
It appears to create some sort of conflict when I attempt to take actions on a Jira dashboard (atlassian.com). I assume it would cause conflicts on other sites that also use some sort of lodash function.

Disabled all extensions and was able to execute successfully, enabling just the ONE wallet extension, it then starts to fail again.

![image](https://user-images.githubusercontent.com/34221002/91465348-4c677680-e853-11ea-8d25-62756253aaec.png)

![image](https://user-images.githubusercontent.com/34221002/91465424-61440a00-e853-11ea-894d-49d3ef659324.png)

**Comment by raptor1001** [comment]
@michaelotis Is this fixed in the new version?

**Comment by michaelotis** [comment]
@raptor1001 Yes, it appears to be. Thanks!
