### ISSUE TITLE
error signing transaction -> transaction failed:nonce too low

### ISSUE THREAD

**Issue by thelostone-mc** [harmony-one/onewallet#73]
### Description 

```
 let rpcURL = 'https://api.s0.b.hmny.io'; // i've also tried with `https://api.s0.t.hmny.io`

  let hmy = new HarmonyJs.Harmony(rpcUrl, {
    chainType: HarmonyUtils.ChainType.Harmony,
    chainId: HarmonyUtils.ChainID.HmyTestnet
  });

```

```
  const txn = hmy.transactions.newTx({
    from: from, // what is returned from harmonyExt.login()
    to: to,
    value: new HarmonyUtils.Unit(amount).asOne().toWei(),
    gasLimit: '31000',
    shardID: 0,
    toShardID: 0,
    gasPrice: new hmy.utils.Unit(amount).asGwei().toWei(),
  });

  console.log(txn);

  const signedTxn = await harmonyExt.wallet.signTransaction(txn);
  const txnHash = await signedTxn.sendTransaction(); // FAILS HERE with nonce too low 
  console.log(txnHash);
```

On sending transaction -> i get the message 
`transaction failed:nonce too low`

The from address is https://explorer.pops.one/#/address/one1crzp6qhczwms38uchngp3xk04ak48ghlky0jkc

It seems to work alright when I do it harmony-core and sign with the private key!
A lil confused if I'm doing something wrong !

Also if i don't pass the gasprice -> does the wallet auto-assign a value to it ?

**Comment by thelostone-mc** [comment]
When i do this 

```
  hmy.wallet.addByPrivateKey('private-key');
  const signedTxn = await hmy.wallet.signTransaction(txn);
  const txnHash = await hmy.blockchain.sendTransaction(signedTxn);
```

it goes through

**Comment by raptor1001** [comment]
@thelostone-mc first of all, I am curious how your second try works
```
 let hmy = new HarmonyJs.Harmony(rpcUrl, {
    chainType: HarmonyUtils.ChainID.HmyTestnet,
    chainId: HarmonyUtils.ChainType.Harmony
  });
```
Here, you are confused the chainID and chainType. `chainid` should be testnet and `chaintype` should be harmony.
If you fix this, I think it should just work. 
>Also if i don't pass the gasprice -> does the wallet auto-assign a value to it ?

No

**Comment by thelostone-mc** [comment]
Ah sorry ! I typed it out wrong while creating the issue!

```
 let hmy = new HarmonyJs.Harmony(rpcUrl, {
    chainId: HarmonyUtils.ChainID.HmyTestnet,
    chainType: HarmonyUtils.ChainType.Harmony
  });
```

is what I've used

**Comment by thelostone-mc** [comment]
@raptor1001 / @NiteeshHarmony any idea what could be causing this?

**Comment by raptor1001** [comment]
hey @thelostone-mc 
This line is not correct https://github.com/thelostone-mc/web/blob/19f2750659a482fe0249ac266700e82b29f2a908/app/assets/v2/js/lib/harmony/utils.js#L94
It should be `new hmy.utils.Unit(1).asGwei().toWei()`. Gas price doesn't mean the amount.

**Comment by thelostone-mc** [comment]
> Also for a dapp making this invocation , 
is there an API i can invoke to find out what the gas price at that given point in time ?
Not super clear on what to set the gasPrice value to.

Ah that's why I was asking regarding this but yeah I'll switch it over to `new hmy.utils.Unit(1).asGwei().toWei()`

**Comment by thelostone-mc** [comment]
@raptor1001 updated the same but still the same error 
https://github.com/thelostone-mc/web/blob/harmony/app/assets/v2/js/lib/harmony/utils.js#L94-L104

I am testing it out in testnet ! Is it possible it's something which happens only in testnet ?

**Comment by raptor1001** [comment]
Refer to this code. This is working one
https://github.com/harmony-one/staking-dashboard/blob/06eaeb546bec7ffda3867a0771b067e399a5ca07/frontend/src/scripts/onewallet-utils.js#L23

**Comment by thelostone-mc** [comment]
the only diff i see if where you 
- convert the from and to address to the checksum value
- I've tried setting the gas limit to 8000 and gas price to `gasPrice: new hmy.utils.Unit(10).asGwei().toWei(),`

The main difference being you've used the npm module while I've used the bundle file generated by running `npm run build` on the `sdk` repo which I've included here https://github.com/thelostone-mc/web/tree/harmony/app/assets/v2/js/lib/harmony

All your variations work when I do a 

```
  hmy.wallet.addByPrivateKey('private-key');
  const signedTxn = await hmy.wallet.signTransaction(txn);
  const response = await hmy.blockchain.sendTransaction(signedTxn);
```

Would you have an example where you've used the bundled version ?

**Comment by thelostone-mc** [comment]
Example of it working with private key signed in code
https://share.vidyard.com/watch/yYEMzKfShy4mC8LVgQK7LC?

Example of the nonce too low error 
https://share.vidyard.com/watch/KP6CzAXD3vo1t3v2Rg1Z6F?

**Comment by thelostone-mc** [comment]
@raptor1001 to make it easier to check, I just spent 30 min setting this up with only the harmony extension integration 
Would appreciate it if you could pull it in and test it out 

https://github.com/thelostone-mc/harmony-test/tree/master

**Comment by raptor1001** [comment]
@thelostone-mc 
import this library
`const { Messenger, Provider } = require("@harmony-js/network");`
https://github.com/thelostone-mc/web/blob/aac95adeb6546158d1331eae136035922023562e/app/assets/v2/js/lib/harmony/utils.js#L50
Change this line with this.
```
    let ext = new HarmonyJs.HarmonyExtension(window.onewallet);
    ext.provider = new Provider("https://api.s0.b.hmny.io").provider;
    ext.messenger = new Messenger(ext.provider, HarmonyUtils.ChainType.Harmony, HarmonyUtils.ChainID.HmyTestnet);
    return ext;
```
You can customize the chaintype and chainid of Messenger.
Let me know if this doesn't work

**Comment by thelostone-mc** [comment]
Tha did the trick !
Thanks a ton @raptor1001
