### ISSUE TITLE
After removing BUSD from tokens-list some weird behaviour

### ISSUE THREAD

**Issue by JB273** [harmony-one/onewallet#76]
Removed the BUSD token on the testnet and see this duplicate LINK on the tokens list:
![image](https://user-images.githubusercontent.com/54506968/97764942-93524080-1b10-11eb-8b19-342952e9320f.png)
The second LINK entry keep searching, as said only on testnet and after removing BUSD.

Can be fixed when removed, but shouldn't be there in the first place.

**Comment by JB273** [comment]
When removing the LINK from here both entries disappear, so might be a bug after all (generates duplicate entry after removing BUSD token)

**Comment by sophoah** [comment]
Same behavior identified, keep spinning,
