### ISSUE TITLE
Onewallet doesnt show amount in transactions

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/onewallet#9]
Ideally we should see how much of the HRC token we have sent out and there are no incoming transactions shown:

![wallet](https://user-images.githubusercontent.com/55639830/87209409-06416c80-c312-11ea-87f4-61b6c8f432f5.png)

**Comment by BrunoMarshall** [comment]
Confirm the same  as mindstyle, shows **0** for BUSD , for normal tx  shows correct)
![image](https://user-images.githubusercontent.com/35432495/87218378-5f30f500-c352-11ea-8ad9-00e8a91017f0.png)

**Comment by raptor1001** [comment]
is fixed
