### ISSUE TITLE
UI Problems with onewallet extension

### ISSUE THREAD

**Issue by taqyon** [harmony-one/onewallet#97]
# Hi guys! 

I have a problem with the application interface, it looks like this: 

<details>
<summary>Pic</summary>

![Снимок экрана 2021-05-27 в 14 28 13](https://user-images.githubusercontent.com/14002721/119818389-cc606100-bef7-11eb-905d-0d3bc39bc494.png)

</details>

### What's up
When you call the application, the interface is cut for some reason. I can't interact with the top part of the application. 

#### Haromy Onewallet
Ver: 1.2.1

#### Google Chrome
Ver: 91.0.4472.77 (Official), (x86_64)

#### Mac OS
Ver: Mac OS Big Sur 11.4 (20F71)

**Comment by taqyon** [comment]
One guy from chrome extensions have the same issue: 
![Снимок экрана 2021-05-27 в 14 33 00](https://user-images.githubusercontent.com/14002721/119818946-8061ec00-bef8-11eb-96ca-723720d2c1f3.png)

**Comment by jtrag** [comment]
Same here...  I'm having the same issue.  I can't send ONE to buy something that's currently very low and going up in price.  I want to get it before it goes up much more but I'm missing the opportunity because of this.  It already went up by 10% while I was trying to get Harmony wallet extension to work properly.  I'm missing opportunity/money here!  Please help!  lol

**Comment by taqyon** [comment]
> Same here... I'm having the same issue. I can't send ONE to buy something that's currently very low and going up in price. I want to get it before it goes up much more but I'm missing the opportunity because of this. It already went up by 10% while I was trying to get Harmony wallet extension to work properly. I'm missing opportunity/money here! Please help! lol
> 
> Brave Web Browser : Version 1.25.68 Chromium: 91.0.4472.77 (Official Build) (x86_64)
> 
> Latest version of Harmony Wallet extension from Chrome Extensions site.
> 
> Mac OS (Latest Version) iMac 27" 5k Retina

its funny, but you can use [MS Edge Browser](https://www.microsoft.com/en-us/edge), it works properly on it: 
![Снимок экрана 2021-05-27 в 22 12 03](https://user-images.githubusercontent.com/14002721/119884022-df475580-bf38-11eb-8501-eca5dfac42cc.png)

---

it seems problen in last google chrome version

**Comment by jtrag** [comment]
> > Same here... I'm having the same issue. I can't send ONE to buy something that's currently very low and going up in price. I want to get it before it goes up much more but I'm missing the opportunity because of this. It already went up by 10% while I was trying to get Harmony wallet extension to work properly. I'm missing opportunity/money here! Please help! lol
> > Brave Web Browser : Version 1.25.68 Chromium: 91.0.4472.77 (Official Build) (x86_64)
> > Latest version of Harmony Wallet extension from Chrome Extensions site.
> > Mac OS (Latest Version) iMac 27" 5k Retina
> 
> its funny, but you can use [MS Edge Browser](https://www.microsoft.com/en-us/edge), it works properly on it:
> 
> ![Снимок экрана 2021-05-27 в 22 12 03](https://user-images.githubusercontent.com/14002721/119884022-df475580-bf38-11eb-8501-eca5dfac42cc.png)
> 
> it seems that problem in last google chrome version

I was thinking the same thing.  Must be an update to Chromium because Brave browser just updated when I restarted it and now Harmony Wallet extension is cut off at the top and I can't use it.  Before that it was fine.

**Comment by taqyon** [comment]
Try edge, so you don't waste your time

**Comment by jtrag** [comment]
It seems that something they updated in Chromium broke the extension.  Developers are supposed to stay on top of these things before they are officially released and pushed out to the masses.  It's usually as simple as using the latest development version of Chromium or other browsers, to test the Harmony extension and make sure it's good to go before the code goes into a release/stable version of the browser.  C'mon Harmony Wallet Devs!  Get with the program!  lol I'm just joking around ;-P it's all good it happens.  Actually, thanks for all of the hard work you put into this. 👍

**Comment by taqyon** [comment]
There is some info i found in harmony chat:

>>Here's a temp fix you can do each time you want to use it; it'll reset back to the issue when you open it again but this works.

>Click on extension and then hit "tab", repeat this sequence until the wallet extension is small enough for you to use it.

>You can also paste this into a new tab and it should work as well. 
chrome-extension://fnnegphlobjdpkhecapkijjdkgcjhkib/popup.html#/home

**Comment by JB273** [comment]
Doesn't work for me on Edge either!

![image](https://user-images.githubusercontent.com/54506968/120084812-98da2e00-c0d3-11eb-8911-f6735d9d79f8.png)

**Comment by taqyon** [comment]
> Doesn't work for me on Edge either! Testing with testnet connection...
> 
> ![image](https://user-images.githubusercontent.com/54506968/120084812-98da2e00-c0d3-11eb-8911-f6735d9d79f8.png)

try this: https://github.com/harmony-one/onewallet/issues/97#issuecomment-850853720

**Comment by jtrag** [comment]
I just turned on Developer Mode in extensions on Brave and did a manual update, and the Harmony Wallet is now working properly!  👍

**Comment by taqyon** [comment]
there is new release: https://github.com/harmony-one/onewallet/releases/tag/v1.2.2
i think this problem would disappear soon

**Comment by taqyon** [comment]
The problem has been solved and is no longer relevant

**Comment by taqyon** [comment]
big thanks to https://github.com/ethlocker
